src/Entity/Books.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BooksRepository")
 */
class Books
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $property;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="integer")
     */
    private $parution;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $editor;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $copy;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return ( new Slugify() )->slugify( $this->title );
    }

    public function getProperty(): ?string
    {
        return $this->property;
    }

    public function setProperty(?string $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getParution(): ?int
    {
        return $this->parution;
    }

    public function setParution(int $parution): self
    {
        $this->parution = $parution;

        return $this;
    }

    public function getEditor(): ?string
    {
        return $this->editor;
    }

    public function setEditor(string $editor): self
    {
        $this->editor = $editor;

        return $this;
    }

    public function getCopy(): ?int
    {
        return $this->copy;
    }

    public function setCopy(?int $copy): self
    {
        $this->copy = $copy;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Books;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('property')
            ->add('synopsis')
            ->add('parution')
            ->add('editor')
            ->add('copy')
            ->add('price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Books::class,
        ]);
    }
}

src/Controller/Admin/AdminBookController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use App\Repository\BooksRepository;
use App\Entity\Books;
use App\Form\BookType;

class AdminBookController extends AbstractController
{
    /**
     * @var BookRepository
     */
    private $repository;
    
     /**
     * @var ObjectManager
     */
    private $em;
    
    /**
     * 
     */
    public function __construct( BooksRepository $repository,ObjectManager $em )
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route( "/admin", name="admin.book.index" )
     * @return Response
     */
    public function index()
    {
        $books = $this->repository->findAllOrder();

        return $this->render( 'admin/book/index.html.twig', compact( 'books' ) );
    }

    /**
     * @Route( "/admin/new", name="admin.book.new" )
     * @return Response
     */
    public function new(Request $request)
    {
        
        $book = new Books();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        
        if ( $form->isSubmitted() && $form->isValid() )
        {
            $this->em->persist( $book );
            $this->em->flush();
            $this->addflash( 'success', 'Enregistrement effectué avec succés' );
            return $this->redirectToRoute( 'admin.book.index' );
        }

         return $this->render( 'admin/book/new.html.twig', [
            'book' => $book,
            'form' => $form->createView()
        ] );        
    }

    /**
     * @Route( "/admin/{id}", name="admin.book.edit" )
     * @return Response
     */
    public function edit(Books $book, Request $request)
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ( $form->isSubmitted() && $form->isValid() )
        {
            $this->em->flush();
            $this->addflash( 'success', 'Modification effectuée avec succés' );
            return $this->redirectToRoute( 'admin.book.index' );
        }

        return $this->render( 'admin/book/edit.html.twig', [
            'book' => $book,
            'form' => $form->createView()
        ] );
    }

    /**
     * @Route( "/admin/delete/{id}", name="admin.book.delete" )
     * @return Response
     */
    public function delete(Books $book, Request $request)
    {
        if ( $this->isCsrfTokenValid( 'delete' . $book->getId(), $request->get( '_token' ) ) )
        {
            $this->em->remove( $book );
            $this->em->flush();
            $this->addflash( 'success', 'Suppression effectuée avec succés' );
        }
        
        return $this->redirectToRoute( 'admin.book.index' );
    }

}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\BooksRepository;
use App\Entity\Books;

class BookController extends AbstractController
{
    /**
     * @var BooksRepository
     */
    private $repository;

    /**
     * 
     */
    public function __construct(BooksRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route( "/book", name="book.index" )
     * @return Response
     */
    public function index():Response
    {
        $books = $this->repository->findAllOrder();
        
        return $this->render( 'book/index.html.twig', [
            'current_menu' => 'book'
        ]);
    }

    /**
     * @Route( "/book/{id}", name="book.show" )
     * @return Response
     */
    public function show($id):Response
    {
        $book = $this->repository->find( $id );
        
        return $this->render( 'book/show.html.twig', [
            'book' => $book,
            'current_menu' => 'book'
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Twig\Environment;
use App\Repository\BooksRepository;
use App\Entity\Books;

class HomeController extends AbstractController
{    
    /**
     * Display home page with latest books
     * @param BooksRepository $repository
     * @return Response
     */
    public function index(BooksRepository $repository):Response
    {
        $books = $repository->findLatest();
        
        return $this->render( 'pages/home.html.twig', [
            'books' => $books
        ] );
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Librairie Lorem Ipsum{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path( 'home' ) }}">Ma Librairie</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if current_men is defined and current_menu == 'book' %}active{% endif %}" href="{{ path( 'book.index' )}}">Les livres</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

templates/book/index.html.twig
{%  extends 'base.html.twig' %}

{% block title %}Tous nos livres{% endblock %}

{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            <h1>Tous nos livre</h1>
            
        </div>
    </div>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title book.title %}

{% block body %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
            </div>
            <div class="col-md-4">
                <h1>{{ book.title }}</h1>
                <div class="text-primary">{{ book.price | number_format( 2, '.', ' ' )}} €</div>
                <a href="#" class="btn btn-primary">Ajouter</a>
            </div>
        </div>
        <p>{{ book.property | nl2br }}
    </div>
{% endblock %}

templates/pages/home.html.twig
{%  extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            <h1>Librairie Lorem Ipsum</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </div>

    <div class="container">
        <h2>Les derniers livres</h2>
        <div class="row flex">
            {% for book in books %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                <p> {{ book.id }}</p>
                                <p> {{ book.slug }}</p>
                                <a href="{{ path( 'book.show', { id: book.id } ) }}">{{ book.title }}</a>
                                <p class="card-text">{{ book.synopsis }}</p>
                                <div class="text-primary">{{ book.price | number_format( 2, '.', ' ' )}} €</div>
                            </h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
    